version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./ddl:/docker-entrypoint-initdb.d"
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    working_dir: "/work/go-cli-sandbox"
    volumes:
      - ".:/work/go-cli-sandbox"
      - "./.data/go-pkg:/go/pkg/mod/cache"
    env_file:
      - docker-compose-default.env
    depends_on:
      - mysql
    restart: on-failure
